services:
# backend API service
- type: web
  name: youtube-study-backend
  runtime: python3
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --no-access-log
  envVars:
    - key: GEMINI_API_KEY
      sync: false
  disk:
    name: chroma-storage
    mountPath: /opt/render/project/data
    sizeGB: 1

# frontend web service
- type: web
  name: youtube-study-frontend
  runtime: python3
  buildCommand: pip install -r requirements.txt
  startCommand: streamlit run streamlit.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
  envVars:
    - key: API_URL
      fromService:
        type: web
        name: youtube-study-backend
        property: url
